apiVersion: v1 
kind: Pod
metadata:
    name: app-pod
    labels:
          app: app
          type: mvc
spec:
  containers:  
    - name: app-pod
      image: sergiolo/apilab01v1.0
      ports:
        - containerPort: 8080   